### ISSUE TITLE
Case insensitive header search

### ISSUE THREAD

**Issue by baransel** [ITUBIDB/MimeD#11]
"mimeD -h To" must extract "To" field from e-mail. This field can be either "To", "to", "tO" or "TO" in input data. It must search header string in case insensitive mode.
The case insensitive mode can be enabled by an optional parameter.

Expected result: output of "mimeD -h Field" should be same with the outout of "mimeD -h FIELD"

**Comment by karakayasemi** [comment]
resolved with https://github.com/ITUBIDB/MimeD/commit/9751fb817ec3f86d580b781e07b0e315aef61705
