### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by dgkncelik** [ITUBIDB/MimeD#5]
Mime headers which doesnt have any mime encoded words, can have chars which their ascii value over 127. This headers must convert with proper charset. That charset could determine with "Content-type" mail header.

**Comment by karakayasemi** [comment]
Please share example mail

**Comment by dgkncelik** [comment]
`------------------------------------------
Subject: M����nlar!
from: eXXXXXX@itu.edu.tr
To: XXXX  G��XXXXX@itu.edu.tr>

Content-Type: text/plain; charset=ISO-8859-9
------------------------------------------`
Theese are the mail headers of the mail. As can be seen there is no mime encoded headers. (I copy the exactly from mail file). Bu chars in "subject" and "to" headers are single ASCII chars which have to be convert to unicode / utf-8. Using charset information in content-type header can fix the situation and single char codes according to ISO-8859-9 fits just right. I couldnt find any other option to determine charset rather then content-type header.
